version: '3.7'
services:
  devcontainer:
    image: cosmomd/medplum-client:1.0
    build: .
    container_name: medplum-client-devcontainer
    hostname: medplum-client-dev.local
    working_dir: /usr/app
    volumes:
      - ..:/usr/app/medplum-client
    command: sleep infinity
